"""Render the case result as markdown.

No timestamp, deliberately — like case 02. The report dates itself by the
observation cutoff, so a `git diff` on it means a number moved, not that someone
ran it again.
"""

from __future__ import annotations

from .estimators import detectable_from_standard_error
from .pipeline import CaseResult


def _pct(value: float) -> str:
    return f"{value:.1%}"


def _pp(value: float) -> str:
    """Percentage points, signed — the unit of every effect in this case."""
    return f"{value * 100:+.2f} pp"


def _mag(value: float) -> str:
    """Percentage points as a magnitude, for quantities with no direction.

    A minimum detectable effect is a size, not a change; printing it with a
    leading ``+`` invites it to be read as one.
    """
    return f"{abs(value) * 100:.2f} pp"


def _interval(estimate) -> str:
    return f"[{estimate.ci_low * 100:+.2f}, {estimate.ci_high * 100:+.2f}]"


def _yes_no(value: bool) -> str:
    return "yes" if value else "no"


def render(result: CaseResult) -> str:  # noqa: C901 - a report is a long sequence of sections
    lines: list[str] = []
    add = lines.append

    retention = result.retention
    q1, q3 = retention[0], retention[1]
    truth = result.truth
    pooled = result.pooled_itt
    save = result.save_rate

    add("# Campaign incrementality — results")
    add("")
    add("Generated by `uv run run.py`. Every number below is reproducible from the seed;")
    add("nothing here is hand-entered. Synthetic data — see `../data-model/DATA_CARD.md`.")
    add("")

    # --- setup ------------------------------------------------------------
    add("## The setup")
    add("")
    add("Two retention campaigns ran against the same base. Both selected their audience the same way — "
        "customers the targeting model thought were at risk — and both then **held a share of that audience "
        "back**, contacting nobody in it. That held-back group is the only reason any of this is answerable.")
    add("")
    add("| | Contacted | Held back | Accepted the offer | Churn (contacted) | Churn (held back) |")
    add("|---|---:|---:|---:|---:|---:|")
    for r in retention:
        a = r.audience
        exposed_churn = sum(a.outcomes(a.exposed)) / len(a.exposed)
        add(f"| {a.campaign.name} ({a.campaign.channel}, {a.campaign.month[:7]}) | {len(a.exposed):,} "
            f"| {len(a.control):,} | {len(a.responded):,} | {_pct(exposed_churn)} | {_pct(a.control_churn)} |")
    add("")
    add(f"The outcome is churn in the 90 days after {retention[0].audience.cutoff} — the same label case 02 predicts. "
        f"Across both campaigns {result.audience_size:,} distinct customers were targeted, and "
        f"{result.overlap:,} of them by both.")
    add("")

    # --- the four readings -------------------------------------------------
    add("## Four readings of the same campaign")
    add("")
    add("![Four readings](readings.svg)")
    add("")
    add("The same customers, the same outcome, four ways of asking whether the campaign worked. The first "
        "three are available without a control group, which is why they are the ones that get reported.")
    add("")
    add("| Reading | Estimate | 95% interval | What it actually measures |")
    add("|---|---:|:---:|---|")
    for e in result.naive:
        add(f"| {e.name} | {_pp(e.value)} | {_interval(e)} | {e.question} |")
    add(f"| **Exposed vs held back (ITT)** | **{_pp(pooled.value)}** | {_interval(pooled)} "
        f"| **What running the campaign did** |")
    add("")
    add("The first two say the campaign made things **worse** — customers who took a retention offer churn "
        f"{_mag(result.naive[0].value)} *more* than the base. That is not a campaign failing; it is the "
        "targeting working. Retention offers went to people who were already leaving, so any comparison "
        "against the untargeted measures who was chosen, not what was done to them.")
    add("")
    add(f"The third fixes that by comparing inside the audience — responders against the people the same "
        f"campaign also picked but who ignored it — and the sign flips to a spectacular {_pp(result.naive[2].value)}. "
        f"It is still wrong, and more dangerously so, because it looks like it controlled for something. "
        f"Accepting an offer is a *choice*, and the customers who take one differ from the ones who ignore it "
        f"in exactly the ways that predict churn.")
    add("")
    add("Only the last row compares groups separated by nothing but a coin flip.")
    add("")

    # --- disagreement ------------------------------------------------------
    add("## The same experiment, run twice, disagrees with itself")
    add("")
    add("Both campaigns are the same design on the same population. Read separately:")
    add("")
    add("| Campaign | ITT | 95% interval | Significant? | Smallest effect it could detect |")
    add("|---|---:|:---:|:---:|---:|")
    for r in retention:
        add(f"| {r.audience.campaign.campaign_id} | {_pp(r.itt.value)} | {_interval(r.itt)} "
            f"| {_yes_no(r.itt.significant)} | {_mag(r.minimum_detectable)} |")
    add(f"| **Pooled** | **{_pp(pooled.value)}** | {_interval(pooled)} | {_yes_no(pooled.significant)} "
        f"| {_mag(detectable_from_standard_error(pooled.standard_error))} |")
    add("")
    add(f"One campaign reports **nothing at all** ({_pp(q1.itt.value)}). The other reports a large, "
        f"statistically significant save ({_pp(q3.itt.value)}, interval excluding zero). A team holding only "
        f"the second would launch a programme on it. A team holding only the first would cancel one.")
    add("")
    add("The last column is why they can both be true at once: neither campaign could reliably detect an "
        f"effect smaller than about {_mag(min(r.minimum_detectable for r in retention))}, and nothing this "
        f"campaign does is anywhere near that big.")
    add("")

    # --- ground truth ------------------------------------------------------
    if truth is not None:
        add("## Opening the answer key")
        add("")
        add("The data model records what each customer would have done had the campaign never run — the same "
            "customer, the same random draw, one counterfactual flip. That makes an identity available that "
            "no real readout has:")
        add("")
        add("> **observed difference = the effect the campaign delivered + the imbalance the coin flip handed over**")
        add("")
        add("![Decomposition](decomposition.svg)")
        add("")
        add("| Campaign | Observed | Delivered by the campaign | Handed over by the flip | Luck bigger than effect? |")
        add("|---|---:|---:|---:|:---:|")
        for r in retention:
            d = r.decomposition
            add(f"| {r.audience.campaign.campaign_id} | {_pp(d.observed)} | {_pp(d.delivered)} "
                f"| {_pp(d.imbalance)} | {_yes_no(d.imbalance_dominates)} |")
        add("")
        add(f"**Neither headline was about the campaign.** The first campaign delivered "
            f"{_pp(q1.decomposition.delivered)} and reported nothing, because the flip happened to hand its "
            f"contacted group {_pp(q1.decomposition.imbalance)} of extra churn — cancelling the effect almost "
            f"exactly. The second delivered {_pp(q3.decomposition.delivered)} and reported "
            f"{_pp(q3.decomposition.observed)}, because its flip ran the other way. In both, the luck was "
            f"larger than the effect.")
        add("")
        add("Both estimates were nonetheless *correct* — each interval covers its own true value. Unbiased "
            "does not mean right on the day: it means right on average over experiments nobody runs twice.")
        add("")
        add(f"Pooled, the estimate lands at {_pp(pooled.value)} against a truth of "
            f"{_pp(result.true_delivered)} — a gap of {_pp(pooled.value - result.true_delivered)}. "
            f"**The arithmetic was never the problem.** The pooled number is essentially exact and its "
            f"interval still runs from {_pp(pooled.ci_low)} to {_pp(pooled.ci_high)}, so it cannot rule out "
            f"the campaign doing nothing whatsoever.")
        add("")
        add(f"One number explains the whole section: of {len(truth.effect):,} customers, the campaign changed "
            f"the outcome of **{truth.n_affected}**. An offer only matters to a customer whose churn sat "
            f"between the treated and untreated probabilities; everyone else was staying, or leaving, either "
            f"way. That is what a few percentage points of effect looks like from the inside, and it is why "
            f"seeing it takes thousands of people rather than hundreds.")
        add("")

    # --- CACE --------------------------------------------------------------
    add("## Effect of *contacting* vs effect of the *offer*")
    add("")
    add("The ITT answers what running the campaign did, averaged over an audience most of whom ignored it. "
        "Rescaling by how much treatment the contact actually delivered gives the effect on the people who "
        "accepted — the complier effect. It is legitimate here because a held-back customer cannot accept an "
        "offer they were never sent, so the extra outcomes in the contacted arm have to have arrived through "
        "the extra offers taken.")
    add("")
    add("| Quantity | Estimate | 95% interval |")
    add("|---|---:|:---:|")
    add(f"| Extra acceptances per contact (first stage) | {_pp(result.pooled_compliance.value)} "
        f"| {_interval(result.pooled_compliance)} |")
    add(f"| Effect per contacted customer (ITT) | {_pp(pooled.value)} | {_interval(pooled)} |")
    add(f"| Effect per customer who accepted (CACE) | {_pp(result.pooled_cace.value)} "
        f"| {_interval(result.pooled_cace)} |")
    if truth is not None:
        add(f"| *True effect per customer who accepted* | *{_pp(truth.cace)}* | *known exactly* |")
    add("")
    add(f"The two effects differ by a factor of about "
        f"{abs(result.pooled_cace.value / pooled.value):.1f} — the reciprocal of the response rate. Quoting "
        f"the second where the first belongs is the most common way a campaign readout inflates itself, and "
        f"it does not require anyone to lie: both numbers are real, and they answer different questions. "
        f"**Only the ITT is a return on the campaign**, because the campaign paid to contact everyone, "
        f"including the majority who ignored it.")
    add("")
    add(f"The control arm is not untreated, incidentally: {_pct(sum(1 for c in q1.audience.control if c in q1.audience.treated) / len(q1.audience.control))} "
        f"of the customers held back from the first campaign accepted an offer from the *other* one. Because "
        f"the two assignments were independent that contaminates nothing — it is balanced across the arms — "
        f"but it does shrink the gap the effect is spread over, which is precisely what the first stage "
        f"measures and divides out.")
    add("")

    # --- negative control --------------------------------------------------
    add("## The falsification test")
    add("")
    add("Two other campaigns ran in the same window — an upsell and a cross-sell. Neither was designed to "
        "affect churn, and in the data model neither does. Running them through the identical machinery is "
        "the check that the machinery is not manufacturing effects:")
    add("")
    add("| Campaign | Objective | ITT on churn | 95% interval | First stage | Wald estimate |")
    add("|---|---|---:|:---:|---:|---:|")
    for r in result.negative_controls:
        wald_cell = ("**nonsense — no first stage**" if r.weak_first_stage
                     else f"{_pp(r.cace.value)}")
        add(f"| {r.audience.campaign.campaign_id} | {r.audience.campaign.objective} | {_pp(r.itt.value)} "
            f"| {_interval(r.itt)} | {_pp(r.compliance.value)} | {wald_cell} |")
    add("")
    add("Both intervals cover zero, which is the result the design predicts and therefore evidence the "
        "estimator is doing what it claims.")
    add("")
    add("The last column is the trap. These campaigns have **no first stage** — being sent an upsell does not "
        "make anyone accept a retention offer — so the denominator of the Wald estimator is noise around "
        "zero. Divide by it and the numbers explode: ")
    for r in result.negative_controls:
        add(f"- `{r.audience.campaign.campaign_id}` reports a complier effect of {_pp(r.cace.value)} "
            f"— a change in churn larger than churn itself, which is not a quantity that exists — from "
            f"an ITT of {_pp(r.itt.value)} that is indistinguishable from nothing.")
    add("")
    add("Nothing errors. The ratio is arithmetically correct and completely meaningless, and it is meaningless "
        "in the direction that flatters the campaign. **The guard is the first stage, checked before the "
        "ratio is taken, not after it is presented.**")
    add("")

    # --- balance -----------------------------------------------------------
    add("## What the diagnostic you *can* run would have told you")
    add("")
    add("The decomposition above needs the answer key. The balance check does not: it compares the two arms "
        "on everything that was already true before the campaign ran, which — if the flip was fair — should "
        "look alike. Covariates are case 02's feature set, built as of the month before each campaign, so "
        "nothing the campaign could have changed is in them.")
    add("")
    add("| Campaign | Covariates | Beyond two standard errors | Beyond the 0.10 convention | Expected by chance | Verdict |")
    add("|---|---:|---:|---:|---:|---|")
    for r in retention:
        b = r.balance
        add(f"| {r.audience.campaign.campaign_id} | {len(b.covariates)} | {b.n_beyond_noise} "
            f"| {b.n_beyond_convention} | {b.expected_beyond_convention:.1f} | {b.verdict} |")
    add("")
    add(f"It half-works, and the half that fails is the dangerous half. The first campaign — the one whose "
        f"flip cancelled its effect — is flagged: {q1.balance.n_beyond_noise} covariates sit beyond two "
        f"standard errors where chance predicts about one. The second campaign passes cleanly with "
        f"{q3.balance.n_beyond_noise}, and its headline overstates the truth by a factor of "
        f"{abs(q3.decomposition.observed / q3.decomposition.delivered):.1f}.")
    add("")
    add("**So the balance table blessed the misleading result and questioned the honest one.** It is worth "
        "running — it is nearly free and it is the only such check available — but it detects broken "
        "randomisation, not insufficient randomisation, and those fail differently. An imbalance large enough "
        "to swamp a three-point effect is small enough to look ordinary.")
    add("")
    add("The largest imbalances in the flagged campaign, for the record:")
    add("")
    add("| Covariate | Contacted | Held back | Standardised difference |")
    add("|---|---:|---:|---:|")
    for c in q1.balance.worst[:4]:
        add(f"| `{c.name}` | {c.mean_exposed:,.3f} | {c.mean_control:,.3f} | {c.standardised_difference:+.3f} |")
    add("")
    add(f"*(The table also drops covariates that were constant before the campaign — "
        f"{len(q3.balance.covariates) - len(q1.balance.covariates)} more of them for the earlier campaign, "
        f"`retention_offer_taken` among them: it ran before any retention offer existed to have been "
        f"taken, so the column is constant. A covariate with no variance "
        f"cannot be imbalanced, and padding the table with rows that can never fail would make every "
        f"experiment look better balanced than it is.)*")
    add("")

    # --- the exclusion trap -------------------------------------------------
    add("## A population rule that is right for prediction and wrong here")
    add("")
    add("Case 02 excludes customers who churned in the earlier window before scoring anything, and it is "
        "right to: a model should not be judged on people who have already gone. Carrying the same filter "
        "into this analysis is a different act, because **the campaign changed who ends up in the filter**.")
    add("")
    add("| Campaign | ITT on the randomised audience | After excluding earlier churners | Shift | Extra share of the held-back arm removed |")
    add("|---|---:|---:|---:|---:|")
    for e in result.exclusions:
        add(f"| {e.campaign_id} | {_pp(e.full.value)} | {_pp(e.filtered.value)} | {_pp(e.shift)} "
            f"| {_pp(e.differential)} |")
    add("")
    add(f"The filter removes more of the held-back arm than the contacted one, in both campaigns — because "
        f"the campaign worked, so fewer treated customers had churned earlier to be filtered out. The two "
        f"groups that survive are no longer the two groups that were randomised, and the headline moves by "
        f"up to {_pp(max(result.exclusions, key=lambda e: abs(e.shift)).shift)}: more than the entire effect "
        f"being measured.")
    add("")
    add("Whether it moves toward the truth or away from it is luck. The rule is not *this filter is bad* — "
        "it is that a causal estimate is defined on the population that was randomised, and every filter "
        "applied after the flip has to be justified against that, no matter how sensible it was upstream.")
    add("")

    # --- heterogeneity ------------------------------------------------------
    add("## Where does the effect live?")
    add("")
    add("The natural next question, and the one that sells uplift modelling: if the effect is concentrated "
        "somewhere, target there. Each audience is split into thirds by a churn score fitted **on untreated "
        "customers only** — fitting it on everyone would learn part of the treatment effect and then be used "
        "to locate the treatment effect.")
    add("")
    for r in retention:
        h = r.heterogeneity
        add(f"**{r.audience.campaign.campaign_id}**")
        add("")
        add("| Stratum | Contacted | Held back | Mean predicted risk | Estimated effect | 95% interval | True effect | True effect on those who accepted |")
        add("|---|---:|---:|---:|---:|:---:|---:|---:|")
        for s in h.strata:
            true_cell = _pp(s.true_effect) if s.true_effect is not None else "—"
            treated_cell = _pp(s.true_effect_on_treated) if s.true_effect_on_treated is not None else "—"
            add(f"| {s.label} | {s.n_exposed} | {s.n_control} | {_pct(s.mean_risk)} "
                f"| {_pp(s.estimate.value)} | {_interval(s.estimate)} | {true_cell} | {treated_cell} |")
        add("")
    add("Two findings, and the second is the one that matters.")
    add("")
    add(f"**The experiment cannot resolve any of this.** The widest stratum interval spans "
        f"{max(r.heterogeneity.widest_interval for r in retention) * 100:.0f} percentage points against an "
        f"estimated spread between "
        f"the extreme strata of {_pp(q1.heterogeneity.spread)} and {_pp(q3.heterogeneity.spread)}. Splitting "
        f"an underpowered experiment into three makes three underpowered experiments. Every stratum interval "
        f"covers every other stratum's estimate, so the ordering — which looks tidy and monotone in the "
        f"second campaign — carries no information.")
    add("")
    add(f"**And there is nothing to find.** The last column is a population quantity rather than a "
        f"sample one, and it is flat: an accepted offer is worth about "
        f"{_mag(sum(s.true_effect_on_treated for r in retention for s in r.heterogeneity.strata) / 6)} "
        f"of churn probability in every stratum of both campaigns. What moves a stratum's ITT is how many of its "
        f"members happened to accept — which runs one way in the first campaign and the other way in the "
        f"second, the signature of noise rather than structure.")
    add("")
    add("So there is no uplift-based targeting rule here, and an experiment this size could not have found "
        "one if there were. That is a narrower conclusion than case 02's — where re-sorting the same "
        "probabilities by expected value moved profit by two thirds — and the difference is instructive: "
        "**ranking who to call is a modelling problem and this data supports it; ranking by measured "
        "incremental effect is a measurement problem and this data does not.**")
    add("")

    # --- the debt ----------------------------------------------------------
    add("## Paying off case 02")
    add("")
    add("Case 02 priced its contact list with a **save rate of "
        f"{_pct(save.assumed)}** — the share of would-be churners a contact retains — and said plainly that "
        "the number was assumed, that no observational data could establish it, and that this case was where "
        "it would be settled. The experiment measures it directly:")
    add("")
    add("    save rate = −ITT ÷ churn rate in the held-back arm")
    add("")
    add("| | Value |")
    add("|---|---:|")
    add(f"| Churn among the held back (would-be churners per contact) | {_pct(save.control_churn)} |")
    add(f"| Incremental saves per contact | {_mag(pooled.value)} of churn prevented |")
    add(f"| **Measured save rate** | **{_pct(save.value)}** |")
    add(f"| 95% interval | {_pct(save.ci_low)} to {_pct(save.ci_high)} |")
    add(f"| Assumed by case 02 | {_pct(save.assumed)} |")
    if save.true_value is not None:
        add(f"| *True value* | *{_pct(save.true_value)}* |")
    add("")
    add("Two statements are both true, and only one of them is knowable without the answer key.")
    add("")
    add(f"The experiment **cannot reject case 02's assumption**: {_pct(save.assumed)} sits inside the "
        f"interval. It cannot reject zero either — the interval runs from {_pct(save.ci_low)} to "
        f"{_pct(save.ci_high)}, which spans *the campaign does nothing* and *the campaign is better than "
        f"case 02 assumed*. On the evidence, case 02's number survives.")
    if save.true_value is not None:
        add("")
        add(f"And case 02's number was **wrong by a factor of {save.assumption_error:.1f}** — the truth is "
            f"{_pct(save.true_value)}. The measurement was closer ({_pct(save.value)}), which is not a "
            f"vindication of the measurement so much as a coincidence at this sample size.")
    add("")
    add("That is the useful finding for a retention team, and it is not a save rate. It is that **the "
        "experiment as designed cannot tell them whether their planning assumption is right, wrong, or "
        "describing a campaign that does nothing.** The fix is not a better estimator. It is a bigger "
        "held-back group.")
    add("")

    if result.repricing:
        add("### What that does to case 02's decision")
        add("")
        add("Case 02's contact list, re-priced at each save rate. The model, the probabilities and the "
            "budget are identical — only the assumption moves.")
        add("")
        add("| Save rate | | Profit, ranked by risk | Profit, ranked by expected value | Difference | Best capacity |")
        add("|---|---:|---:|---:|---:|---:|")
        for row in result.repricing:
            add(f"| {row.label} | {_pct(row.save_rate)} | {row.profit_by_risk:,.0f} | {row.profit_by_value:,.0f} "
                f"| {row.uplift:+,.0f} | {row.optimal_contacts:,} |")
        add("")
        assumed_row = result.repricing[0]
        measured_row = result.repricing[1]
        add(f"Case 02's headline — that re-sorting the same probabilities by expected value is worth "
            f"{assumed_row.uplift:+,.0f} at a fixed budget — **survives**, at "
            f"{measured_row.uplift:+,.0f}. The ranking never depended on the save rate: it is a positive "
            f"constant common to every customer's expected value, so it cannot reorder anybody. What it "
            f"changes is the *level*, and therefore how many people are worth calling at all — the optimal "
            f"capacity moves from {assumed_row.optimal_contacts:,} contacts to "
            f"{measured_row.optimal_contacts:,}.")
        add("")
        add("That is the honest summary of the damage: case 02's *decision* was robust to the assumption it "
            "flagged, and its *business case* was not.")
        add("")

    # --- power -------------------------------------------------------------
    add("## How big the held-back group needed to be")
    add("")
    add("![Power](power.svg)")
    add("")
    add("| | Value |")
    add("|---|---:|")
    add(f"| Effect actually there | {_pp(-result.target_effect)} |")
    add(f"| Held back, per campaign | {len(q1.audience.control):,} and {len(q3.audience.control):,} |")
    for r in retention:
        add(f"| Chance {r.audience.campaign.campaign_id} alone called it significant "
            f"| {_pct(r.power_against(result.target_effect))} |")
    add(f"| Chance the two pooled did | {_pct(result.realised_power)} |")
    add(f"| Held back needed per campaign, for an 80% chance | {result.required_control:,} |")
    add("")
    add(f"The design had roughly an {_pct(q1.power_against(result.target_effect))} chance of finding what was "
        f"there — so about four campaigns in five come back empty. Two ran here and one came back "
        f"significant, which is already better luck than the design deserved. The answer key adds the "
        f"detail that makes the point: **the campaign that reached significance was the one that "
        f"delivered less.**")
    add("")
    add(f"Pooling both helped and was not enough: {_pct(result.realised_power)}, still short of the 80% bar "
        f"and still an interval covering zero. Reaching it needs about {result.required_control:,} customers "
        f"held back per campaign — against the {len(q1.audience.control):,} actually held back, close to "
        f"{result.required_control / len(q1.audience.control):.0f}× more. A sample-size calculator asked "
        f"for one balanced experiment would say {result.required_equal_arms:,} per arm — the gap is not a "
        f"discount, it is bookkeeping: {result.required_control:,} counts customers *held back*, across two "
        f"campaigns, each of which also contacts "
        f"{len(q1.audience.exposed) / len(q1.audience.control):.1f} people for every one it holds back.")
    add("")
    add("Two things worth separating, because the instinct is to fix the wrong one. Raising the held-back "
        f"share from {_pct(len(q1.audience.control) / len(q1.audience)):s} to half would shrink the interval "
        "by under a tenth: the binding constraint is the **audience**, not the split. Measuring the outcome "
        "in a window right after the campaign rather than months later would help more. Pooling campaigns "
        "deliberately — as a standing measurement programme rather than two separate readouts — would help "
        "most, and costs nothing that is not already being spent.")
    add("")

    # --- limitations -------------------------------------------------------
    add("## Limitations")
    add("")
    add("- **The outcome is measured long after the campaign.** The data model carries one labelled window, "
        f"so the effect of a campaign in {q1.audience.campaign.month[:7]} is read against churn "
        f"{q1.audience.cutoff[:7]} onward. The generator's effect is permanent, so nothing decays here; in a "
        "real operation it would, and measuring that far out would understate a campaign that worked.")
    add("- **The two pooled estimates share customers.** "
        f"{result.overlap:,} of {result.audience_size:,} targeted customers were in both audiences, so the "
        "two ITTs are not independent and the pooled interval is slightly narrower than it should be. It "
        "does not change the verdict — the interval covers zero comfortably either way — but a "
        "customer-level clustered analysis would be the correct treatment.")
    add("- **Pooling across campaigns has a trap this case sidesteps rather than solves.** Treating "
        "\"exposed to either campaign\" as one arm would break the randomisation, because being in two "
        "audiences is itself a marker of risk. Each campaign is therefore estimated separately and combined "
        "by precision, which is valid; a stratified analysis by targeting pattern would use the overlap "
        "rather than working around it.")
    add("- **One draw of one world.** Every conclusion about luck here rests on the two randomisations that "
        "happened. Re-running the generator across many seeds would turn \"the imbalance exceeded the "
        "effect\" from an observation into a distribution.")
    add("- **Synthetic data with a known generating process.** That is what makes the answer key possible, "
        "and it also means the estimator is never tested against what breaks real experiments: crossovers, "
        "spillovers between customers, contact-policy overrides, audiences rebuilt mid-flight.")
    add("- **Consent and eligibility are not enforced here.** The audiences are taken as the campaign built "
        "them. Case 03 has to confront who was *allowed* to be contacted.")
    add("")

    # --- deployability -----------------------------------------------------
    add("## What would make this good enough to run on")
    add("")
    add("Stated as design rules, not aspirations:")
    add("")
    add(f"- Every retention campaign holds back a control group sized from a **stated minimum detectable "
        f"effect**, not from a habit. At this base rate and a {_mag(result.target_effect)} target, that "
        f"is about {result.required_control:,} held back per campaign.")
    add("- The readout reports the ITT, the first stage and the interval together. A complier effect is "
        "published only when the first stage is strong, and never as the campaign's return.")
    add("- Results accumulate across campaigns by design, so the programme answers a question no single "
        "campaign is large enough to answer.")
    add("- A campaign with no plausible mechanism on the outcome is run through the same pipeline every "
        "cycle as a falsification test. When it starts reporting effects, the pipeline is broken.")
    add("- Filters applied after randomisation are justified against the randomised population, or dropped.")
    add("- The save rate in the planning model is dated, carries its interval, and is refreshed from the "
        "accumulated experiments rather than inherited.")
    add("")

    return "\n".join(lines) + "\n"
