"""Actionable segmentation — and the four ways a segmentation stops being one.

A segment that carries a name and a chart is a description. A segment that
carries an action has to survive four questions the description never faces:

1. **Are the axes measuring anything?** RFM is computed here as prescribed, on
   the transaction table, and then measured. In a subscription two of its three
   letters are constants — recency has no variance at all, and frequency is
   tenure under another name — because the transaction is generated by the
   company's billing run rather than by the customer's decision to return.
2. **Does the segment last?** The data model has two observation cutoffs, so the
   same rule can be applied twice. Nearly half the base changes cell in six
   months, essentially all of it on the risk axis; the value axis barely moves.
   The grid crosses a photograph with a film.
3. **Can the action be delivered?** Judged against case 03's permission layer,
   reachability falls monotonically as risk rises — the cell whose action is the
   only profitable one is the cell least able to receive it.
4. **Does it change what anyone does?** The playbook's contact list is priced
   against the continuous ranking with case 02's own accounting. The ranking
   wins, and that is the useful result: a grid is not a worse way to answer
   "who", it is an answer to a different question.

Standard library only, like the rest of the track: every number in the report is
auditable line by line and CI validates it without installing anything.
"""

from .audit import CausalAudit, SegmentEffect
from .data import RiskModel, Snapshot, build_snapshot, load_tables
from .decision import ContactList, DecisionTest
from .grid import Cuts, Play, Segment, Trait, build_segments, load_playbook, quantile_cuts
from .pipeline import MEASURED_SAVE_RATE, CaseResult, run_case
from .reach import (
    Deliverability,
    PermissionView,
    PolicyReach,
    build_permissions,
    deliverability,
    falls_with_risk,
    policy_reach,
    risk_band_gap,
)
from .rfm import Letter, classic_rfm, correlation, engagement_recency
from .stability import Migration

__all__ = [
    "MEASURED_SAVE_RATE",
    "CaseResult",
    "CausalAudit",
    "ContactList",
    "Cuts",
    "DecisionTest",
    "Deliverability",
    "Letter",
    "Migration",
    "PermissionView",
    "PolicyReach",
    "Play",
    "RiskModel",
    "Segment",
    "SegmentEffect",
    "Snapshot",
    "Trait",
    "build_permissions",
    "build_segments",
    "build_snapshot",
    "classic_rfm",
    "correlation",
    "deliverability",
    "engagement_recency",
    "falls_with_risk",
    "policy_reach",
    "risk_band_gap",
    "load_playbook",
    "load_tables",
    "quantile_cuts",
    "run_case",
]
