"""The markdown written to ``outputs/report.md``.

Every figure is read off the result object. Nothing is hand-entered, so the
report cannot drift from the run that produced it — and a number that changes in
a diff means the *analysis* changed, which is the only reason a committed output
is worth committing.
"""

from __future__ import annotations

from .pipeline import CaseResult

RULE_LABELS = {
    "require_channel_consent": "no opt-in on that channel",
    "min_days_since_last_contact": "inside the cool-off window",
    "max_contacts_per_365d": "at the yearly contact cap",
    "max_failed_invoices_6m": "in arrears",
    "block_if_unresolved_escalation": "open unresolved complaint",
    "ELIG_FAMILY": "offer not sold to that plan family",
    "ELIG_NOT_AN_UPGRADE": "already on that plan or better",
}


def _pct(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"


def _pp(value: float) -> str:
    return f"{value * 100:+.2f} pp"


def _money(value: float) -> str:
    return f"{value:,.0f}"


def _yes(value: bool) -> str:
    return "yes" if value else "no"


def _join(items: list[str], empty: str = "none") -> str:
    """`a`, `a and b`, `a, b and c` — the report is prose, not a debug dump."""
    if not items:
        return empty
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def _header(result: CaseResult) -> list[str]:
    wave = result.wave
    return [
        "# Governed next-best-offer — results",
        "",
        "Generated by `uv run run.py`. Every number below is reproducible from the seed;",
        "nothing here is hand-entered. Synthetic data — see `../data-model/DATA_CARD.md`.",
        "",
        "## The decision",
        "",
        f"One wave, decided at **{wave.cutoff}**: {len(wave):,} customers in scope "
        f"({wave.excluded_already_churned:,} dropped because they left during the earlier "
        f"window), a contact capacity of **{wave.capacity:,}**, and "
        f"{len(result.priced)} offers with response history to choose between.",
        "",
        "Risk comes from case 02's model, refitted here rather than quoted. The save rate is "
        f"the **{_pct(result.economics.base.save_rate)}** case 05 measured against its control "
        "group, not the 25% case 02 had to assume.",
        "",
    ]


def _policy(result: CaseResult) -> list[str]:
    lines = [
        "## The rules, as data",
        "",
        "The contact policy lives in the shared data model (`contact_policy`), not in this "
        "code. That is a deliberate modelling choice: a policy that lives in the scoring "
        "script is not a policy, it is a preference — unauditable without reading Python, "
        "and different in every team's copy.",
        "",
        "| Rule | Applies to | Value | Why |",
        "|---|---|---:|---|",
    ]
    for rule in result.policy.rules.values():
        applies = "everything" if "all" in rule.applies_to else _join(sorted(rule.applies_to))
        unit = rule.unit[:-1] if rule.value == 1 and rule.unit.endswith("s") else rule.unit
        value = "required" if rule.unit == "flag" else f"{rule.value:,.0f} {unit}"
        lines.append(f"| `{rule.policy_id}` | {applies} | {value} | {rule.rationale} |")
    lines += [
        "",
        "Eligibility is separate and comes from the offer catalogue "
        "(`offers.eligible_family`, `offers.upgrade_to_rank`): whether an offer *makes sense* "
        "for a customer is a product rule, not a compliance one, and the two have different "
        "owners and different failure modes.",
        "",
    ]
    return lines


def _compliance(result: CaseResult) -> list[str]:
    lines = [
        "## What the campaigns that already ran would fail",
        "",
        "Cases 02 and 05 take these audiences exactly as the campaign built them. Judged "
        "against the two rules that can be checked in hindsight — consent on the delivery "
        "channel, and whether the offer was even applicable — most of what ran was not "
        "permitted.",
        "",
        "| Campaign | Channel | Contacted | Had opted in | Offer applicable | Both |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for row in result.compliance:
        lines.append(
            f"| {row.name} | {row.channel} | {row.exposed:,} | {_pct(row.consent_rate)} | "
            f"{_pct(row.eligible_rate)} | {row.compliant:,} |"
        )

    worst = min(result.compliance, key=lambda r: r.consent_rate)
    least_eligible = min(result.compliance, key=lambda r: r.eligible_rate)
    quietest = min(result.channel_reach, key=lambda c: result.channel_reach[c])
    aside = (" — the channel with the lowest opt-in in the base — "
             if worst.channel == quietest
             else f" — while the base's least-consented channel is *{quietest}* — ")
    lines += [
        "",
        f"**{worst.name}** went out by *{worst.channel}*{aside}"
        f"so {_pct(1 - worst.consent_rate)} of the people it contacted had "
        "never agreed to be contacted that way. Nothing in the campaign report would show "
        "this: the response rate is computed over everyone contacted, and a customer who "
        "never opted in still answers the phone.",
        "",
        f"**{least_eligible.name}** is the other failure. It offered "
        f"*{least_eligible.offer_id}* to {least_eligible.exposed:,} customers, of whom only "
        f"{_pct(least_eligible.eligible_rate)} were on a plan the offer would actually "
        "improve. The rest were sent an upgrade to the plan they already had, or to a worse "
        "one. That is not a compliance breach — it is a broken product rule, and it costs "
        "response rather than fines.",
        "",
    ]
    return lines


def _consent(result: CaseResult) -> list[str]:
    lines = [
        "## Permission is not a random sample",
        "",
        "The first thing to check about a gate is whether the people it removes look like "
        "the people it keeps. For consent they do not — and not uniformly across channels.",
        "",
        "| Channel | Opted in | Churn if opted in | Churn if not | Gap | Bigger than its noise? |",
        "|---|---:|---:|---:|---:|:---:|",
    ]
    for profile in result.consent_profiles:
        lines.append(
            f"| {profile.channel} | {_pct(profile.opt_in_rate)} | "
            f"{_pct(profile.churn_opted_in)} | {_pct(profile.churn_opted_out)} | "
            f"{_pp(profile.gap)} | {_yes(profile.resolvable)} |"
        )

    resolvable = [p for p in result.consent_profiles if p.resolvable]
    lines += [
        "",
        "In the data model engaged customers opt in more, and weak engagement is a churn "
        "driver, so consent and risk are linked by construction. The size of that link is "
        "the interesting part: it is visible on "
        + _join([f"**{p.channel}**" for p in resolvable], empty="no channel")
        + " and not on the others, and even where it is visible it is worth a couple of "
        "points. The customers you are allowed to call churn a little less than the ones "
        "you are not.",
        "",
        f"{result.unreachable:,} customers of {len(result.wave):,} have opted out of every "
        "channel. They are not a targeting problem; they are unreachable, and any plan that "
        "counts them in its addressable base is overstating it.",
        "",
    ]
    return lines


def _gates(result: CaseResult) -> list[str]:
    base = result.realised_churn_of(result.wave.customer_ids)
    lines = [
        "## What each gate actually removes",
        "",
        "![What each gate removes](gates.svg)",
        "",
        "Three counts, because one would mislead. **Pairs blocked** is every refusal a rule "
        "makes; **sole blocker** counts only the refusals that dropping that one rule would "
        "reverse; **customers removed** is the operational number — customers whose *best* "
        "offer this rule refuses.",
        "",
        "| Rule | Pairs blocked | Sole blocker | Customers removed | Their modelled risk | Their actual churn |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for cost in result.rule_costs:
        removed = f"{cost.customers_removed:,}"
        risk = _pct(cost.mean_churn_probability) if cost.customers_removed else "—"
        actual = _pct(cost.realised_churn_rate) if cost.customers_removed else "—"
        lines.append(
            f"| `{cost.policy_id}` — {RULE_LABELS.get(cost.rule, cost.rule)} | "
            f"{cost.blocked_pairs:,} | {cost.sole_blocker_pairs:,} | {removed} | {risk} | {actual} |"
        )

    lines += ["", f"The wave's own churn rate is **{_pct(base)}**. A gate that removed a random "
              "slice of the base would sit on that number. None of them do, and they miss it in "
              "different directions:", ""]

    removers = [c for c in result.rule_costs if c.customers_removed]
    riskiest = max(removers, key=lambda c: c.realised_churn_rate, default=None)
    if riskiest is not None:
        lines += [
            f"- **`{riskiest.policy_id}` removes the customers most likely to leave** — "
            f"{riskiest.customers_removed:,} customers who went on to churn at "
            f"{_pct(riskiest.realised_churn_rate)}, against a base of {_pct(base)}. It is not "
            "a targeting rule and nobody thinks of it as one, but it is the most selective "
            "thing in the policy. The mechanism is circular: they were contacted last "
            "quarter *because* they were high risk, and they are barred this quarter for "
            "having been contacted.",
        ]

    zero = [c for c in result.rule_costs if not c.customers_removed]
    if zero:
        names = ", ".join(f"`{c.policy_id}`" for c in zero)
        blocked = sum(c.blocked_pairs for c in zero)
        lines += [
            f"- **{names} block {blocked:,} pairs and remove nobody.** The offers they refuse "
            "were never anyone's best offer, so the refusal changes no decision. This is the "
            "whole reason the first column is a bad cost metric — and note it does not "
            "contradict the audit above: a campaign *sent* those ineligible offers; an engine "
            "that scores them simply never picks them.",
        ]
    lines.append("")
    return lines


def _cooloff(result: CaseResult) -> list[str]:
    chosen = result.policy.value_of("min_days_since_last_contact", 0.0)
    points = result.sensitivity
    steps: list = []
    for point in points:
        if not steps or point.blocked_customers != steps[-1].blocked_customers:
            steps.append(point)

    lines = [
        "## The cool-off window is a step, not a dial",
        "",
        "![Cool-off sensitivity](cooloff.svg)",
        "",
        "Campaigns happen on dates, so a rule written in days is flat until it crosses one "
        "and then jumps. Sweeping the window:",
        "",
        "| Cool-off | Customers suppressed | Their modelled risk | Reachable | Plan expected value |",
        "|---:|---:|---:|---:|---:|",
    ]
    for point in points:
        risk = _pct(point.mean_churn_probability_blocked) if point.blocked_customers else "—"
        lines.append(
            f"| {point.value:,.0f} d | {point.blocked_customers:,} | {risk} | "
            f"{point.reachable_customers:,} | {_money(point.plan_expected_value)} |"
        )

    lines += [
        "",
        f"The policy is set at **{chosen:,.0f} days**. At 180 it suppresses nobody; the last "
        "campaign is just outside the window. A month further out and it suppresses "
        f"{steps[1].blocked_customers:,} customers whose modelled risk is "
        f"{_pct(steps[1].mean_churn_probability_blocked)} — the retention audience from two "
        "quarters ago, arriving in one lump.",
        "",
        "Widen it further and the suppressed group *grows and gets safer*, because the window "
        "starts reaching campaigns that were not targeted on risk. The cost of this rule is "
        "not a smooth trade-off anybody tuned. It depends on where the edge falls relative to "
        "a campaign calendar nobody consulted when the number was written down.",
        "",
    ]
    return lines


def _plans(result: CaseResult) -> list[str]:
    comparison = result.comparison
    assert comparison is not None
    governed, suppressed, ungoverned = comparison.governed, comparison.suppressed, comparison.ungoverned

    lines = [
        "## Three lists",
        "",
        "![From promised plan to sendable list](plans.svg)",
        "",
        "The same scores and the same rules, assembled three ways.",
        "",
        "| List | Contacts | Capacity used | Expected value | Modelled risk | Actual churn | Retention profit booked |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for plan in (ungoverned, governed, suppressed):
        profit, n = result.realised[plan.name]
        lines.append(
            f"| {plan.name} | {len(plan):,} | {_pct(plan.fill_rate)} | "
            f"{_money(plan.expected_value)} | {_pct(plan.mean_churn_probability)} | "
            f"{_pct(plan.realised_churn_rate(result.labels))} | {_money(profit)} over {n} contacts |"
        )

    lines += [
        "",
        f"**Governance costs {_money(comparison.governance_cost)} of expected value** "
        f"({_pct(comparison.governance_cost / ungoverned.expected_value)} of the ungoverned "
        "plan). That is the number worth arguing about, and it is the smaller one.",
        "",
        f"**Doing the same governance in the wrong order costs "
        f"{_money(comparison.ordering_cost)} more** — "
        f"{comparison.ordering_cost / comparison.governance_cost:.1f}× the rules themselves. "
        "Ranking first and suppressing afterwards sends "
        f"**{len(suppressed):,} contacts against a capacity of {suppressed.capacity:,}**: "
        f"{comparison.unfilled_capacity:,} slots are freed by suppressed customers and never "
        "refilled. Nothing errors. The campaign reports that it contacted the top of the "
        f"list, and it contacted {_pct(suppressed.fill_rate)} of it.",
        "",
        "The last two columns are the part that is not about money. The ungoverned list "
        f"contacts customers who went on to churn at {_pct(ungoverned.realised_churn_rate(result.labels))}; "
        f"the governed list, {_pct(governed.realised_churn_rate(result.labels))}. The rules do "
        "not scale the programme down — they point it somewhere else. Only "
        f"{_pct(governed.overlap_with(ungoverned))} of the governed list appears in the "
        "ungoverned one.",
        "",
        "The offer mix moves with it:",
        "",
        "| List | " + " | ".join(o.offer_id for o in result.priced) + " |",
        "|---|" + "---:|" * len(result.priced),
    ]
    for plan in (ungoverned, governed, suppressed):
        mix = plan.offer_mix()
        lines.append(f"| {plan.name} | " + " | ".join(
            f"{mix.get(o.offer_id, 0):,}" for o in result.priced) + " |")
    lines.append("")
    return lines


def _speculative(result: CaseResult) -> list[str]:
    if not result.unpriced or result.speculative is None:
        return []
    governed = result.comparison.governed  # type: ignore[union-attr]
    speculative = result.speculative
    unpriced = result.unpriced[0]
    taken = speculative.offer_mix().get(unpriced.offer_id, 0)

    return [
        "## The offer nobody has ever sent wins the auction",
        "",
        f"The catalogue has {len(result.priced) + len(result.unpriced)} offers. "
        f"**{unpriced.offer_id}** (*{unpriced.name}*) has never been in a campaign, so there "
        "is no response history behind it and no honest way to estimate acceptance for it. "
        "It is held out of the plan above.",
        "",
        "Score it anyway — with the acceptance model fitted on the offer that *did* run, "
        "which is what an engine does by default — and it takes "
        f"**{taken:,} of the {speculative.capacity:,} slots** and lifts the plan's expected "
        f"value from {_money(governed.expected_value)} to "
        f"{_money(speculative.expected_value)}, a "
        f"{_pct(speculative.expected_value / governed.expected_value - 1, 0)} improvement "
        "made entirely of an assumption.",
        "",
        f"The mechanism is ordinary: {unpriced.offer_id} moves customers further up the price "
        "ladder than the offer that has history, so the same acceptance probability buys a "
        "bigger margin. There is no variation in the data from which the price sensitivity "
        "could be estimated — one upgrade offer has ever run — so nothing can correct it. "
        "The offer with the least evidence gets the most confident number, and a forecast "
        "built on it will be missed by a wide margin for reasons the model cannot report.",
        "",
    ]


def _acceptance(result: CaseResult) -> list[str]:
    lines = [
        "## The evidence inherits the violation",
        "",
        "The acceptance model is fitted on customers the campaigns contacted. Going forward "
        "the policy only permits contact with the ones who had opted in — so part of the "
        "training data describes a population that can no longer be addressed.",
        "",
        "| Objective | Rows | Rows from permitted contacts | Lost | Acceptance (all) | Acceptance (permitted) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in result.acceptance_comparison:
        lines.append(
            f"| {row.objective} | {row.n_all:,} | {row.n_permitted:,} | "
            f"{_pct(row.training_rows_lost)} | {_pct(row.base_rate_all)} | "
            f"{_pct(row.base_rate_permitted)} |"
        )

    worst = max(result.acceptance_comparison, key=lambda r: r.training_rows_lost)
    lines += [
        "",
        f"The retention model loses **{_pct(worst.training_rows_lost)}** of its evidence this "
        "way. What it does *not* lose, here, is the answer: the acceptance rates barely move "
        f"({_pct(worst.base_rate_all)} against {_pct(worst.base_rate_permitted)}). Reporting "
        "that honestly matters more than the warning does — the evidence base halves and the "
        "estimate survives, on this data, at this size. The general claim a governance "
        "retrofit invites (*'our propensity models are fitted on a population we can no "
        "longer contact'*) is structurally true and, measured, is not always material.",
        "",
    ]
    return lines


def _answer_key(result: CaseResult) -> list[str]:
    lines = [
        "## Opening the answer key",
        "",
        "Everything above is expected value: whether a customer would have accepted an offer "
        "they were never sent is not observable. But the retention campaigns in the data "
        "model *did* run, and the model records what every customer would have done had they "
        "not — so one question can be answered exactly rather than estimated:",
        "",
        "> If those campaigns had only contacted the people they were allowed to, how many "
        "customers would still have been saved?",
        "",
        "![Reach decomposition](reach.svg)",
        "",
        "| Campaign | Contacted | Allowed | Reach kept | Saved | Saved if compliant | Saves kept |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for audit in result.audits:
        reach = audit.reach
        lines.append(
            f"| {audit.name} ({audit.channel}) | {reach.exposed:,} | {reach.permitted:,} | "
            f"{_pct(reach.reach_retained)} | {reach.saves_full} | {reach.saves_permitted} | "
            f"{_pct(reach.saves_retained)} |"
        )

    lines += [
        "",
        "The loss splits exactly in two — fewer people reached, and the people who remain "
        "responding differently:",
        "",
        "> saves(compliant) − saves(as run) = volume + composition",
        "",
        "| Campaign | Volume | Composition | Total | Per-person rate | Bigger than its noise? |",
        "|---|---:|---:|---:|---:|:---:|",
    ]
    for audit in result.audits:
        reach = audit.reach
        lines.append(
            f"| {audit.campaign_id} | {reach.volume:+.1f} | {reach.composition:+.1f} | "
            f"{reach.total:+.1f} | {_pct(reach.rate_full)} → {_pct(reach.rate_permitted)} | "
            f"{_yes(reach.composition_is_resolvable)} |"
        )

    volume = sum(a.reach.volume for a in result.audits)
    composition = sum(a.reach.composition for a in result.audits)
    signs = {a.reach.composition > 0 for a in result.audits}
    worst = min(result.audits, key=lambda a: a.reach.saves_retained)
    best_channel = max(result.channel_reach, key=lambda c: result.channel_reach[c])
    lines += [
        "",
        f"Across both campaigns volume accounts for {volume:+.1f} customers and composition "
        f"{composition:+.1f}. **Compliance is a reach problem, not a targeting problem** — and "
        "the composition term, which is the one a retention team reaches for (*'but the "
        "people who opted in are better customers'*), is "
        + ("not resolvable from noise in either campaign"
           if not any(a.reach.composition_is_resolvable for a in result.audits)
           else "resolvable in only part of the data")
        + (", and the two campaigns do not even agree on its sign." if len(signs) > 1 else "."),
        "",
        "The consequence for the worst-hit campaign is blunt: "
        f"{worst.name} contacted {worst.reach.exposed:,} customers and "
        f"changed the outcome for {worst.reach.saves_full}. Restricted to the "
        f"{worst.reach.permitted:,} it was allowed to contact, it would have "
        f"changed {worst.reach.saves_permitted}.",
        "",
        f"Reach on the channel it used ({worst.channel}) is "
        f"{_pct(result.channel_reach[worst.channel])}; on the best-consented channel "
        f"({best_channel}) it is {_pct(result.channel_reach[best_channel])}. Delivering "
        "the same offer somewhere the customer agreed to hear it needs no new assumption "
        "about effectiveness to move the term that dominates.",
        "",
    ]
    return lines


def _limitations(result: CaseResult) -> list[str]:
    return [
        "## What this does not settle",
        "",
        "- **Consent is recorded without an effective date**, so the retrospective audit "
        "judges past campaigns against *today's* opt-ins. A customer who opted out after "
        "being contacted is scored here as having been contacted without permission. The "
        "data model states this limitation plainly (`DATA_CARD.md`); in a real audit, "
        "consent-as-of-the-send-date is the only defensible version and its absence is "
        "usually the first finding, not a footnote.",
        "- **The forward-looking list is scored in expectation, not measured.** No control "
        "group was held back from it, so its value is a plan, not a result — the same "
        "position case 02 was in before case 05 ran.",
        "- **An offer's effect is assumed to be channel-independent.** Moving a retention "
        "offer from `call` to `push` changes reach, which is measurable here, and probably "
        "changes response, which is not: no campaign in the data model ran the same offer on "
        "two channels, so there is no variation to estimate it from.",
        "- **The acceptance model transfers across offers within an objective.** That is why "
        f"{result.unpriced[0].offer_id if result.unpriced else 'an unrun offer'} is held out "
        "rather than scored, but the same criticism applies in weaker form to every offer "
        "whose terms differ from the campaign that trained the model.",
        "- **The retention arithmetic charges the offer only when it works**, inherited from "
        "case 02's `Economics`. A real discount is given to everyone who accepts, including "
        "the customers who were staying anyway.",
        "- **The counterfactual covers the campaigns that ran, not the list this case "
        "builds.** The answer key can price the compliance cost of history; it cannot "
        "validate a plan for the future.",
        "- **One draw of one world.** The step in the cool-off curve sits where it does "
        "because of one campaign calendar. Many seeds would turn every claim here about "
        "*how much* into a distribution.",
        "",
    ]


def render(result: CaseResult) -> str:
    sections = (
        _header(result)
        + _policy(result)
        + _compliance(result)
        + _consent(result)
        + _gates(result)
        + _cooloff(result)
        + _plans(result)
        + _speculative(result)
        + _acceptance(result)
        + _answer_key(result)
        + _limitations(result)
    )
    return "\n".join(sections).rstrip() + "\n"
