"""The markdown written to ``outputs/report.md``.

Every figure is read off the result object. Nothing is hand-entered, so the
report cannot drift from the run that produced it — and a number that changes in
a diff means the *analysis* changed, which is the only reason a committed output
is worth committing.
"""

from __future__ import annotations

from .pipeline import CaseResult

# The two product rules, as a reader would say them. Same wording case 03 uses,
# so a reader moving between the two reports is not learning new names.
RULE_LABELS = {
    "ELIG_FAMILY": "offer not sold to that plan family",
    "ELIG_NOT_AN_UPGRADE": "already on that plan or better",
}


def _pct(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"


def _money(value: float) -> str:
    return f"{value:,.0f}"


def _article(word: str) -> str:
    """`a` or `an` — the offer types are read into a sentence, not a slot."""
    return "an" if word[:1].lower() in "aeiou" else "a"


def _plural(count: int, singular: str, plural: str | None = None) -> str:
    return f"{count:,} {singular if count == 1 else (plural or singular + 's')}"


def _join(items: list[str], empty: str = "none") -> str:
    if not items:
        return empty
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def _header(result: CaseResult) -> list[str]:
    after = result.after
    return [
        "# Actionable segmentation — results",
        "",
        "Generated by `uv run run.py`. Every number below is reproducible from the seed;",
        "nothing here is hand-entered. Synthetic data — see `../data-model/DATA_CARD.md`.",
        "",
        "## The decision",
        "",
        f"The base is to be segmented at **{after.cutoff}** — {len(after):,} customers, "
        f"{result.test.excluded_already_churned:,} dropped because they left during the earlier "
        "window — and each segment is to carry an action for next quarter.",
        "",
        "Risk is case 02's churn model, refitted here rather than quoted. Value is the same "
        "monthly revenue that case feeds its economics. The save rate behind every expected "
        f"value is the **{_pct(result.economics.save_rate)}** case 05 measured, not the 25% "
        "case 02 had to assume.",
        "",
        "The axes are cut into equal thirds. Quantiles rather than round thresholds, "
        "deliberately: a rule like *risk above 20%* has to be defended and re-defended as the "
        "base rate moves, and this case is not about defending one. Equal thirds are arbitrary "
        "in a way that is visible.",
        "",
    ]


def _rfm(result: CaseResult) -> list[str]:
    letters = result.letters
    repaired = result.repaired_recency
    degenerate = [letter for letter in letters if letter.degenerate]

    lines = [
        "## First, the segmentation everyone already has",
        "",
        "RFM is the default, it is what a segmentation request usually means, and it is "
        "computed here exactly as prescribed — on `billing`, the transaction table of a telco. "
        "Then each dimension is measured.",
        "",
        "| | Dimension | Distinct values | Largest single value covers | Churn gap, top vs bottom fifth |",
        "|---|---|---:|---:|---|",
    ]
    for letter in [*letters, repaired]:
        gap = (f"{_pct(letter.readable_spread)}" if letter.quintiles_separate
               else "**no variation to read**")
        modal = "<1%" if letter.modal_share < 0.005 else _pct(letter.modal_share, 0)
        lines.append(
            f"| `{letter.symbol}` | {letter.name} — {letter.definition} | {letter.distinct:,} | "
            f"{modal} | {gap} |"
        )

    recency = next(letter for letter in letters if letter.symbol == "R")

    lines += [
        "",
        f"**Recency has no variance at all.** A single distinct value across "
        f"{len(recency.values):,} customers — every one of them was invoiced in the most recent "
        "month, because that is what a billing run does. Sorting a constant still produces five "
        "quintiles, and they still come back with different churn rates, entirely from the order "
        "the rows arrived in. That gap is withheld from the table above; printing it is how a "
        "constant becomes a finding.",
        "",
        f"**Frequency is tenure wearing a different name.** Correlation with `tenure_months`: "
        f"**{result.frequency_tenure_correlation:.4f}**. Not strongly related — the same variable. "
        "A customer's invoice count is the number of months they have been a customer, because "
        "the invoice is generated by the billing run rather than by a decision to come back.",
        "",
        "That is the whole mechanism, and it is a property of the business model rather than of "
        "this dataset. RFM reads a customer's repeat-purchase decision. A subscription does not "
        "have one: the company decides when to bill, monthly, until somebody stops it. Two of the "
        "three dimensions are measuring the company's own schedule."
        f"{' Only `M` survives, and `M` is ARPU.' if 'M' not in [d.symbol for d in degenerate] else ''}",
        "",
        f"**The repair is a different event, not a different formula.** Recency rebuilt on app "
        f"logins — something the customer chooses to do — separates churn by "
        f"{_pct(repaired.readable_spread)} between its extreme fifths, against "
        f"{_pct(next(letter.readable_spread for letter in letters if letter.symbol == 'M'))} for "
        "the best of the original three. Recency was always measuring a decision; retail just "
        "happened to be a business where the decision and the transaction were the same event.",
        "",
        "![What each dimension is worth](axes.svg)",
        "",
    ]
    return lines


def _grid(result: CaseResult) -> list[str]:
    profitable = result.profitable_segments
    lines = [
        "## The grid, and what it says to do",
        "",
        "Two axes, because an action needs two answers that no single score gives: *is this "
        "customer leaving?* and *does it matter if they do?* Risk alone spends the retention "
        "budget on customers worth less than the offer; value alone spends it on customers who "
        "were never going anywhere.",
        "",
        "![The grid](grid.svg)",
        "",
        "| Segment | Customers | Modelled risk | ARPU | Actual churn | Profit per customer | Measured profile |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for segment in result.segments:
        traits = "; ".join(trait.phrase() for trait in segment.traits)
        lines.append(
            f"| **{segment.name}** | {len(segment):,} | {_pct(segment.mean_risk)} | "
            f"{segment.mean_value:,.2f} | {_pct(segment.realised_churn)} | "
            f"{segment.expected_value_per_customer:+.2f} | {traits} |"
        )

    lines += [
        "",
        "**The profile column is measured, never written.** Each cell reports the features on "
        "which it departs furthest from the base, in units of the base's own spread. Naming a "
        "cell *disengaged high-value customers* because the name sounds right is how a "
        "segmentation becomes a story, and the story is unfalsifiable by construction.",
        "",
        "What comes back is the data model's own causal design, recovered rather than assumed: "
        "the high-risk cells are the ones with unresolved escalations and falling usage, the "
        "low-risk cells are the ones logging into the app. No cell was told what it should look "
        "like.",
        "",
        f"**{len(result.segments) - len(profitable)} of the {len(result.segments)} cells lose money "
        f"on contact.** Only {_join([f'**{s.name}**' for s in profitable])} "
        f"{'clears' if len(profitable) == 1 else 'clear'} the cost of contacting the average "
        f"member, covering {sum(len(s) for s in profitable):,} of {len(result.after):,} customers. "
        "That is the deliverable, and it is mostly a list of people not to contact — which is the "
        "part of a segmentation that survives meeting a budget.",
        "",
        "Note the cell that separates the two axes: **Let go** carries the same modelled risk as "
        "the rescue cells and a negative expected value, because what it is worth saving is less "
        "than what saving it costs. A risk model alone puts those customers at the top of the list.",
        "",
    ]
    return lines


def _stability(result: CaseResult) -> list[str]:
    honest = result.honest_migration
    naive = result.in_sample_migration
    flows = honest.largest_flows[:4]

    lines = [
        "## Does the segment last long enough to act on?",
        "",
        f"The data model labels two observation cutoffs {honest.months_apart} months apart, so "
        "the same rule can be applied twice and the answer counted instead of assumed.",
        "",
        "![Migration between the cutoffs](drift.svg)",
        "",
        f"**{_pct(honest.share(honest.cell_changed))} of the base changed cell in "
        f"{honest.months_apart} months**, and the two axes are not equally to blame: the risk "
        f"band moved for {_pct(honest.share(honest.risk_band_changed))} and the value band for "
        f"{_pct(honest.share(honest.value_band_changed))}.",
        "",
        "That asymmetry is the structural point. ARPU is the plan the customer is on — a "
        "commercial fact that changes when somebody signs something. Risk is behaviour, and "
        "behaviour is what the model is built to detect moving. **The grid crosses a photograph "
        "with a film**, and inherits the refresh rate of the film.",
        "",
        f"For {_pct(honest.share(honest.contact_decision_changed))} of the base, it is not the "
        "label that changed but the decision: they moved between a cell that contacts and a cell "
        "that does not.",
        "",
        f"**Meanwhile the report looks fine.** The largest change in any segment's share of the "
        f"base is {_pct(honest.size_drift)}. Re-cutting the axes at each refresh keeps every cell "
        f"the same size by construction, so a segment-size dashboard is flat while "
        f"{_pct(honest.share(honest.cell_changed))} of the people inside the segments have swapped "
        "places. Nothing in the aggregate view can show this.",
        "",
    ]
    if flows:
        lines += [
            "The largest moves are a legible deterioration path rather than noise:",
            "",
            "| From | To | Customers |",
            "|---|---|---:|",
        ]
        for (source, target), count in flows:
            lines.append(f"| {source} | {target} | {count:,} |")
        lines.append("")

    lines += [
        f"**This is a floor, and the floor is checked.** Scoring the earlier cutoff with the "
        f"model fitted on it is in-sample — the score has partly memorised those customers, so "
        f"they look more like themselves than they are. Measured that way migration is "
        f"{_pct(naive.share(naive.cell_changed))}; measured cross-fitted, with a model that never "
        f"saw them, {_pct(honest.share(honest.cell_changed))}. The comfortable method understates "
        "the problem, which is the direction that matters, and the figure quoted above is the "
        "honest one.",
        "",
    ]
    return lines


def _delivery(result: CaseResult) -> list[str]:
    rows = result.deliverability
    broken = [row for row in rows if row.play_does_not_apply]
    lines = [
        "## Can the action be delivered?",
        "",
        "A segmentation ends in a sentence like *contact this cell with a retention offer*. "
        "Whether that sentence can be executed is a different question, answered by rules the "
        "analyst does not own, and normally discovered by the campaign team the week before the "
        "send. The rules are not re-implemented here: this is case 03's permission layer, reading "
        "the shared `contact_policy` table, asked per offer type rather than per customer.",
        "",
        "![Deliverability](reach.svg)",
        "",
        "| Segment | Modelled risk | Customers | Reachable under the contact policy |",
        "|---|---:|---:|---:|",
    ]
    for row in result.policy_reach:
        lines.append(
            f"| {row.segment} | {_pct(row.mean_risk)} | {row.members:,} | "
            f"{row.reachable:,} ({_pct(row.reach, 0)}) |"
        )
    lines += [
        "",
        "That column ignores which offer: it is the contact policy on its own. The next one asks "
        "the narrower question — can this cell receive the offer *its play prescribes*?",
        "",
        "| Segment | Action | Customers | Reachable | Refused by policy | Refused by the catalogue |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            f"| **{row.segment}** | send {_article(row.offer_type)} "
            f"{row.offer_type.replace('_', ' ')} | {row.members:,} | "
            f"{row.reachable:,} ({_pct(row.reach, 0)}) | {row.blocked_by_policy:,} | "
            f"{row.blocked_by_eligibility:,} |"
        )

    ordered = sorted(rows, key=lambda r: r.reach)
    low, high = result.reach_low_risk_third, result.reach_high_risk_third
    lines += [
        "",
        "**The policy leans against the cells that need it.** Judged on whether a customer can "
        "receive *any* offer — which is the only version in which the nine cells are comparable, "
        f"since a play's own reach also depends on its channel — the lowest-risk third of the "
        f"base is reachable at {_pct(low)} and the highest-risk third at {_pct(high)}, a gap of "
        f"{(low - high) * 100:.1f} points.",
        "",
        "The mechanism is not a coincidence: arrears, an open unresolved complaint and a recent "
        "contact are simultaneously the rules that suppress a contact and the facts the risk "
        "model reads as danger. Case 03 measured this gate by gate; here it lands on the plan.",
        "",
        "**What is not claimed:** that reachability falls monotonically with risk. "
        + ("It does not — cell by cell the ordering breaks, and "
           if not result.reach_falls_with_risk else
           "On this run it happens to, but that is not evidence: ")
        + "nine cells of a few hundred customers cannot support a nine-step ordering. The direction "
        "of the gap between the extreme thirds holds across seeds; its *size* does not — on a "
        "smaller world with less contact history it shrinks to a couple of points. So the "
        "mechanism is worth designing around and the number is not worth quoting as a constant.",
        "",
    ]
    if broken:
        plural = len(broken) > 1
        lines += [
            f"**{'Two plays in this playbook are' if plural else 'One play in this playbook is'} "
            f"not a delivery problem — {'they are' if plural else 'it is'} wrong.** "
            f"{_join([f'*{row.segment}*' for row in broken])} "
            f"{'are' if plural else 'is'} refused more often by the catalogue than by any policy, "
            "and the two cases fail for different reasons:",
            "",
        ]
        for row in broken:
            breakdown = _join([
                f"{count:,} attributed to *{RULE_LABELS.get(rule, rule)}*"
                for rule, count in sorted(row.eligibility_reasons.items(), key=lambda kv: (-kv[1], kv[0]))
            ])
            head = (f"- **{row.segment}** — {row.blocked_by_eligibility:,} of {row.members:,} "
                    f"customers have *every* offer of this type refused by a product rule; "
                    f"{breakdown}.")
            if row.dominant_reason == "ELIG_NOT_AN_UPGRADE":
                lines.append(
                    f"{head} The cell is the highest-value third of the base, and the "
                    "highest-value third is, mechanically, the customers already at the top of "
                    "the plan ladder. The action contradicts the definition of the segment it "
                    "was written for."
                )
            else:
                lines.append(
                    f"{head} The play asks for the plan that *fits* a low-usage customer, which "
                    "is a move down the ladder. Every offer of this type is a move up — "
                    "`upgrade_to_rank` only points at a higher rank — so the nearest available "
                    "offer type was the one it got coded to. The catalogue has no entry for what "
                    "this segment actually needs, and a play cannot be more executable than the "
                    "catalogue it draws on."
                )
        lines += [
            "",
            f"{'They are' if plural else 'It is'} left in, and reported, rather than quietly "
            "fixed. Nothing errors when a play does not apply; the campaign simply under-delivers "
            "and the segmentation is not suspected. Separating the two refusal families is what "
            "makes it visible at all — a single *unreachable* count would have buried it next to "
            "a consent problem, which has an entirely different remedy.",
            "",
        ]
    lines += [
        f"The best-served play reaches {_pct(ordered[-1].reach, 0)} of its cell; the worst, "
        f"{_pct(ordered[0].reach, 0)}.",
        "",
    ]
    return lines


def _decision(result: CaseResult) -> list[str]:
    test = result.decision
    assert test is not None
    lines = [
        "## Does the grid change what anyone does?",
        "",
        "The question a segmentation is rarely asked. The same budget is spent twice on the same "
        "customers — once by the continuous ranking cases 02 and 03 already publish, once by the "
        "playbook — and both lists are priced with case 02's own profit accounting, imported "
        "rather than restated, so the comparison cannot be won by redefining value.",
        "",
        "| List | Contacts | Realised profit | Actual churn of those contacted |",
        "|---|---:|---:|---:|",
        f"| ranked by expected value | {len(test.by_expected_value):,} | "
        f"{_money(test.by_expected_value.realised_profit)} | {_pct(test.by_expected_value.realised_churn)} |",
        f"| chosen by the playbook | {len(test.by_segment):,} | "
        f"{_money(test.by_segment.realised_profit)} | {_pct(test.by_segment.realised_churn)} |",
        "",
        f"The two lists agree on {_pct(test.overlap)} of their names, and the ranking wins by "
        f"{_money(test.profit_gap)} — {_pct(test.profit_gap_share)} of the profit, at identical "
        "capacity. Discretising a score into thirds throws away the ordering inside each third, "
        "and the budget stops precisely inside one of them.",
        "",
        "**That is not an argument against segmenting.** It is an argument against segmenting for "
        "*this*. The comparison is only possible because both methods were pointed at one "
        "question — *who gets the next contact* — and a single number answers that better than a "
        "grid can, which should not be surprising.",
        "",
        f"What the ranking does not produce is everything else: it assigns no action to the "
        f"{test.non_contacting_customers:,} customers it never reaches, and it does not say what "
        f"to send the ones it does. The playbook carries "
        f"{_plural(test.distinct_offer_types, 'distinct offer type')} and "
        f"{_plural(len(result.segments) - test.contacting_segments, 'play')} that involve no "
        "outbound contact at all. A ranking has no opinion on any of it.",
        "",
        "So the honest division of labour is the one the numbers support: **rank to choose who, "
        "segment to choose what.** Using the grid as the selector costs "
        f"{_pct(test.profit_gap_share)} for nothing, because the ranking was already there.",
        "",
    ]
    return lines


def _causal(result: CaseResult) -> list[str]:
    audit = result.causal
    assert audit is not None
    strongest = audit.strongest
    lines = [
        "## The question that comes next, and has no answer here",
        "",
        "*Which segment responded best?* It sounds like reporting. Answering it gives the "
        "segmentation a causal claim it was never designed to support.",
        "",
        "Case 05 established the ceiling: pooled over the whole base, the retention experiment "
        "could not distinguish a 25% save rate from 11%, or from zero. Cutting the same "
        "experiment by segment divides that evidence again. Read against the answer key — what "
        "each customer would have done had the campaign never run — this is what is left:",
        "",
        "| Segment | Treated | Outcomes the campaign actually changed | True mean effect |",
        "|---|---:|---:|---:|",
    ]
    for effect in audit.effects:
        lines.append(
            f"| {effect.segment} | {effect.treated:,} | {effect.outcomes_changed} | "
            f"{effect.true_effect:+.4f} |"
        )

    lines += [
        "",
        f"Across the entire base the campaign changed **{audit.total_outcomes_changed} outcomes** "
        f"among {audit.total_treated:,} treated customers. Split nine ways that is "
        f"{audit.outcomes_per_segment:.1f} per segment, and "
        f"{'no segment' if audit.readable_segments == 0 else f'{audit.readable_segments} segments'} "
        "reach even ten. Every ordering of these rows is decided by which handful of customers "
        "sat near their own threshold.",
        "",
        "The temptation is real and worth naming: the true effects above are *not* ordered by "
        f"risk — the strongest belongs to **{strongest.segment if strongest else 'n/a'}**, not to "
        "the segment the whole plan is built around. A reader would like that to mean something. "
        "It does not: at these counts the answer key itself is noise, and the correct conclusion "
        "is the same one case 05 reached — **this experiment has no per-segment reading**, and "
        "that is fixed by designing an experiment, not by slicing this one further.",
        "",
        "The table is here because the absence of an answer is the finding. A version of this "
        "analysis that quietly dropped the outcome counts would produce nine plausible effect "
        "sizes and a recommendation.",
        "",
    ]
    return lines


def _limitations(result: CaseResult) -> list[str]:
    return [
        "## Limitations",
        "",
        "- **Equal thirds are a choice, not a finding.** A different cut moves every cell count "
        "and every profile in the grid table. What does not move is the shape of the result: two "
        "axes with different refresh rates, deliverability inversely related to risk, and a "
        "ranking that beats a grid at ranking.",
        "- **One migration measurement, at one gap.** Six months is what the data model labels. "
        "Whether the risk band churns faster or slower over one quarter is not observable here, "
        "and a quarterly plan is the common case.",
        "- **The value axis is current ARPU, not lifetime value.** A customer's worth is what "
        "they pay now, undiscounted, with no expectation of what they would grow into. That "
        "flatters the low-tenure high-usage customers in the grow cells.",
        "- **Deliverability is judged against today's consent**, as case 03 also notes: consent "
        "has no effective date in the data model, so a retrospective read applies present opt-ins "
        "to past decisions.",
        "- **The playbook is one playbook.** Its actions are plausible and one of them is "
        "demonstrably wrong, which is the honest state of a first draft — but the plays are not "
        "evidence, and nothing here validates that a discount is the right response to the rescue "
        "cell. That would take the experiment case 05 shows this data cannot supply.",
        "",
    ]


def render(result: CaseResult) -> str:
    """The full report."""
    sections = [
        _header(result),
        _rfm(result),
        _grid(result),
        _stability(result),
        _delivery(result),
        _decision(result),
        _causal(result),
        _limitations(result),
    ]
    return "\n".join("\n".join(section) for section in sections).rstrip() + "\n"
