"""The markdown written to ``outputs/report.md``.

Every figure is read off the result object. Nothing is hand-entered, so the
report cannot drift from the run that produced it — and a number that changes in
a diff means the *analysis* changed, which is the only reason a committed output
is worth committing.
"""

from __future__ import annotations

from .pipeline import CaseResult


def _pct(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"


def _money(value: float, digits: int = 2) -> str:
    return f"{value:,.{digits}f}"


def _plural(count: int, singular: str, plural: str | None = None) -> str:
    return f"{count:,} {singular if count == 1 else (plural or singular + 's')}"


def _join(items: list[str], empty: str = "none") -> str:
    if not items:
        return empty
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def _header(result: CaseResult) -> list[str]:
    chain = result.value_chain
    fee, contribution = chain[0][1], chain[-1][1]
    return [
        "# ARPU and value decomposition — results",
        "",
        "Generated by `uv run run.py`. Every number below is reproducible from the seed;",
        "nothing here is hand-entered. Synthetic data — see `../data-model/DATA_CARD.md`.",
        "",
        "## The question",
        "",
        f"The base is **{len(result.population):,} customers** at **{result.cutoff}**. Cases 01, 02, 03 and 05",
        "all needed to know what a customer is worth, and all of them used the same number:",
        "trailing three-month billed revenue, times a flat margin, times a flat twelve months.",
        "",
        "This case is about the value itself, so the chain gets taken apart:",
        "",
        "```",
        "product fee → billed ARPU → collected ARPU → contribution → customer value",
        "```",
        "",
        f"Between the first rung and the fourth, the monthly figure falls from **{_money(fee)}** to "
        f"**{_money(contribution)}**, down {_pct(1 - contribution / fee)} — and the last link, the one",
        "that turns a monthly figure into a customer's worth, changes half the target list.",
        "",
        "Each link is changed **on its own**. Changing the revenue definition, the cost model and",
        "the horizon together produces a list that shares half its names with case 02's and",
        "explains nothing about which change did it.",
        "",
    ]


def _base(result: CaseResult) -> list[str]:
    base = result.base
    assert base is not None
    return [
        "## Before the ratio: which revenue, over which customers",
        "",
        "The data model keeps invoicing customers after they churn — its data card says so plainly,",
        f"which is what makes defining the base part of the exercise rather than a lookup. "
        f"{_plural(base.departed_customers, 'customer')} churned in the window that closed at "
        f"**{base.prior_cutoff}**; over the {base.months_after_prior} months since, they were sent "
        f"{_plural(base.phantom_invoices, 'invoice')} worth **{_money(base.phantom_revenue, 0)}**.",
        "",
        f"That is **{_pct(base.phantom_share)} of everything billed** in the period. Nothing in the",
        "data announces it: `billing` is complete, internally consistent, and reconciles with itself.",
        "",
        "| | |",
        "|---|---:|",
        f"| Revenue billed since the earlier cutoff | {_money(base.revenue_after_prior, 0)} |",
        f"| …belonging to customers who had already left | {_money(base.phantom_revenue, 0)} |",
        f"| Share of the revenue line that is not real | **{_pct(base.phantom_share)}** |",
        f"| ARPU as a `GROUP BY` returns it | {_money(base.arpu_with_departed)} |",
        f"| ARPU over customers who were actually there | {_money(base.arpu_live_only)} |",
        f"| Difference | **{_pct(abs(base.arpu_live_only / base.arpu_with_departed - 1), 2)}** |",
        "",
        "The last two rows are the part worth keeping. The revenue line is overstated by "
        f"{_pct(base.phantom_share)} and the account count by about the same, and **ARPU is barely",
        "moved at all** — because the departed customers were worth roughly what everyone else is,",
        "so they cancel between the numerator and the denominator.",
        "",
        "The usual moral about ratios is the opposite one. Here the ratio is the robust metric and",
        "the totals are the dangerous ones, and that is not a law: it holds because this base's",
        "leavers happen to look like its stayers. A business whose churn is concentrated in cheap",
        "customers would see the error in ARPU and not in revenue. Which one is safe is a property",
        "of the base, and it has to be measured rather than remembered.",
        "",
    ]


def _level(result: CaseResult) -> list[str]:
    split, variance, usage, estimator = result.split, result.variance, result.usage, result.estimator
    assert split is not None and variance is not None and usage is not None and estimator is not None

    readable = usage.within_readable
    lines = [
        "## The level: where a unit of revenue comes from",
        "",
        f"Across {split.invoices:,} invoices, **{_pct(variance.between_share, 2)} of the variance in "
        f"what customers are billed is between tariffs**, not within them. What is left is the",
        f"non-fee part of the invoice: {_pct(split.overage_share)} of billed revenue, carrying "
        f"{_pct(variance.within_share, 2)} of its variance.",
        "",
        "So the interesting question is what that residue is made of, and the standard way to ask it",
        "is *do heavy users generate more revenue?*",
        "",
        "| Scope | Rows | Correlation with balance carried |",
        "|---|---:|---:|",
        f"| **all products together** | {usage.overall.n:,} | **{usage.overall.r:+.4f}** |",
    ]
    for link in usage.by_product:
        mark = "" if link.readable else " *"
        lines.append(f"| within {link.scope} | {link.n:,} | {link.r:+.4f}{mark} |")
    lines += [
        "",
        "`*` = smaller than twice its own standard error.",
        "",
        f"Aggregated, the answer is a clear yes: **{usage.overall.r:+.4f}**, over {usage.overall.n:,} rows,",
        "significant by any test anyone would run. Inside a tariff the largest reading in either",
        f"direction is **{usage.largest_within.r:+.4f}** — {usage.ratio:.0f} times smaller than the",
        "aggregate. The product is the confounder: bigger products cost more *and* carry more balance,",
        f"so customers who use more appear to pay more. {_plural(len(readable), 'reading')} of "
        f"{len(usage.by_product)} {'clears' if len(readable) == 1 else 'clear'} its own noise band, which",
        "at twenty thousand rows says nothing except that the sample is large.",
        "",
        "Nothing errors. A pricing team reads the first row, concludes that heavy users are",
        "monetising well, and builds a usage-based add-on for a business that has no usage-based",
        "revenue.",
        "",
        "### Which makes trailing ARPU an estimate of a number already known",
        "",
        f"The value axis in this world has **{estimator.distinct_true_values} true values**: the seven",
        f"tariffs. Measuring it as a {estimator.months_averaged}-month average of billed revenue adds",
        "noise to a price that is on the contract:",
        "",
        "| Product | Fee | Measured ARPU | sd | Noise, as a share of the level |",
        "|---|---:|---:|---:|---:|",
    ]
    for product in estimator.per_plan:
        lines.append(
            f"| {product.product_id} | {_money(product.monthly_fee, 0)} | {_money(product.measured_mean)} | "
            f"{product.measured_sd:.2f} | {_pct(product.relative_sd)} |"
        )
    lines += [
        "",
        f"Around **{_pct(estimator.mean_relative_sd)}** on every tariff. That is not an argument",
        "against measuring revenue — it is an argument that in *this* business the measurement",
        "carries nothing the price list does not, which the correlation table above establishes",
        "rather than assumes. Where usage-based charging is real, the same table would come back",
        "with within-product correlations that mean something, and this section would say the opposite.",
        "",
    ]
    return lines


def _movement(result: CaseResult) -> list[str]:
    bridge = result.bridge
    assert bridge is not None
    first_month, first_arpu, first_n = bridge.first
    last_month, last_arpu, last_n = bridge.last
    step = bridge.largest_step

    return [
        "## The movement: a bridge that has nothing to say, said properly",
        "",
        "The other half of a revenue decomposition is the month-to-month bridge — the movement",
        "attributed to existing customers, joiners and leavers. The identity used here is exact:",
        "",
        "```",
        "ARPU(t) − ARPU(t−1) = within + entry − exit",
        "```",
        "",
        f"where *within* is the paired change across the {step.panel:,} customers present in both",
        "months. It reconciles to floating-point tolerance, and every term carries the standard",
        "error of the mean it is built from.",
        "",
        f"Over {len(bridge.steps)} transitions, **{len(bridge.readable_steps)} clears ±2 standard "
        f"errors** and {bridge.readable_terms} of the {3 * len(bridge.steps)} individual terms do. At a",
        "5% false-positive rate, roughly one and three respectively is what pure noise produces.",
        "",
        "| | |",
        "|---|---:|",
        f"| ARPU, {first_month[:7]} → {last_month[:7]} | {_money(first_arpu)} → {_money(last_arpu)} |",
        f"| Widest gap between any two months | {_money(bridge.level_range)} "
        f"({_pct(bridge.level_range / first_arpu)} of the level) |",
        f"| Customers billed | {first_n:,} → {last_n:,} (+{_pct(bridge.base_growth, 0)}) |",
        f"| Revenue | +{_pct(bridge.revenue_growth, 0)} |",
        f"| Largest single movement | {step.month_to[:7]}: {step.total:+.4f} ± {2 * step.total_se:.4f} |",
        "",
        f"The business grew {_pct(bridge.revenue_growth, 0)} and ARPU did not move. The deliverable of",
        "this section is not the bridge — it is the interval on it. Without one, a monthly review",
        f"spends forty minutes on the {step.total:+.3f} above, which is inside the error of its own",
        "measurement.",
        "",
        "**This world cannot produce anything else, and that is declared rather than discovered.**",
        "Nobody changes tariff in this data model and nobody stops being invoiced, so the two",
        "movements a real ARPU bridge exists to catch — migration and mix-shift-through-churn —"
        " are structurally absent."
        + (" The exit term is exactly zero at every step, not small." if bridge.exit_is_structural_zero
           else ""),
        "The bridge is built, tested and reported anyway, because a decomposition that returns",
        "*nothing happened* and can prove it is a different artefact from one that was never run.",
        "",
    ]


def _collection(result: CaseResult) -> list[str]:
    collection = result.collection
    assert collection is not None
    bottom = min(collection.deciles, key=lambda d: d.collection_rate)

    lines = [
        "## Billed to collected: a level, not a ranking",
        "",
        f"Over the last {collection.months} months, **{_pct(collection.loss_rate, 2)}** of what was",
        f"invoiced to this population was never paid. Timing adds nothing on top: "
        f"{_pct(collection.same_month_share)} of settled invoices are paid inside their own service",
        "month, so the cash view and the accrual view differ by the shortfall and by nothing else.",
        "",
        "The question that would have mattered is whether the shortfall is *distributed*. The data",
        "model gives failed invoices to price-sensitive customers and payment problems raise churn",
        "odds, so the two ought to travel together — and if they did, every value figure in this",
        "track would be overstating exactly the population a retention programme is spent on.",
        "",
        "| Risk decile | Mean predicted churn | Collection rate |",
        "|---:|---:|---:|",
    ]
    for decile in collection.deciles:
        lines.append(
            f"| {decile.rank} | {_pct(decile.mean_risk, 2)} | "
            f"{_pct(decile.collection_rate, 2)} ± {_pct(2 * decile.collection_se, 2)} |"
        )
    low, high = collection.fold_range
    verdict = (
        "clears its own noise band in this run" if collection.concentrates_in_risk
        else "does not clear its own noise band"
    )
    lines += [
        "",
        f"The spread between the best and worst decile is {_pct(collection.spread, 2)} ± "
        f"{_pct(2 * collection.spread_se, 2)}"
        + ("" if collection.monotone else ", and it is not monotone")
        + f" — and the lowest-risk decile ({bottom.rank}) collects *worse* than the highest. Across the",
        "whole population the correlation between predicted risk and collection rate is",
        f"**{collection.risk_correlation:+.4f}**, against a standard error of "
        f"{collection.risk_correlation_se:.4f}: it {verdict}.",
        "",
        "That single number is not worth much either way, which the same base can show without",
        "needing a second world. Split into five folds by stride — same generating process, same",
        "cutoff, just fewer customers each — and re-measure:",
        "",
        "| Fold | Customers | Correlation |",
        "|---:|---:|---:|",
    ]
    for fold in collection.folds:
        mark = "" if fold.readable else " *"
        lines.append(f"| {fold.rank} | {fold.n:,} | {fold.r:+.4f}{mark} |")

    lines += [
        "",
        "`*` = smaller than twice its own standard error.",
        "",
        f"The folds run from {low:+.4f} to {high:+.4f}"
        + (f", changing sign {collection.fold_sign_changes} times along the way. "
           if not collection.sign_is_stable else ", without changing sign. ")
        + f"{collection.readable_folds} of {len(collection.folds)} clear their own band. Nothing is",
        "wrong with any of these measurements; there is simply not much there to measure, and which",
        "sign a single run reports is decided by which customers it happened to contain. Re-running",
        "the whole case at other seeds and sizes says the same thing more slowly — the estimate has",
        "landed anywhere between −0.12 and +0.09 across seven worlds (`--seed 7`, `--seed 2024`,",
        "`--seed 123`, `--customers 800 --months 18`, `--customers 1500 --seed 99`).",
        "",
        "What *is* stable is the magnitude: never past 0.12 in any of them. At that size the",
        "correction to a customer's value is worth about a percentage point of their collection rate —",
        f"smaller than the {_pct(collection.loss_rate, 2)} level correction itself, and far smaller than",
        "anything else in this chain.",
        "",
        f"So collection is a **level correction** — apply {_pct(collection.loss_rate, 2)} once and move",
        "on. It re-prices every customer and re-orders none of them, which is the opposite of what",
        "this section was written expecting.",
        "",
    ]
    return lines


def _contribution(result: CaseResult) -> list[str]:
    sensitivity = result.sensitivity
    model = result.cost_model
    assert sensitivity is not None
    declared = sensitivity.at(model.per_balance)

    lines = [
        "## Collected to contribution: the number nobody owns",
        "",
        "Revenue is not margin. Serving a customer costs a fixed amount per account, something per",
        "thousand of balance carried, and something per support contact — and those unit costs live in",
        "[`cost_model.csv`](../cost_model.csv) rather than in the scoring script, for the reason case",
        "03 gave about the contact policy: an assumption inside code cannot be reviewed by the people",
        "who own it. A cost model has the same problem and one worse property. A contact rule that is",
        "wrong gets argued about by the people it blocks; a marginal cost that is wrong silently",
        "re-orders a customer list, and the list looks exactly the same.",
        "",
        "| Product | Fee | Collected | Balance carried | Support | Contribution |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for product in result.plan_economics:
        lines.append(
            f"| {product.product_id} | {_money(product.monthly_fee, 0)} | {_money(product.collected)} | "
            f"{product.balance_k:,.1f}k | {_money(product.support_cost)} | {_money(product.contribution)} |"
        )

    inversion = sensitivity.inversion_per_balance
    ruin = sensitivity.ruin_per_gb
    lines += [
        "",
        f"At the declared **{_money(model.per_balance)} per 1k of balance** the contribution order is the fee",
        f"order: the top third by revenue and the top third by contribution share "
        f"{_pct(declared.top_third_overlap)} of their names. The decomposition, run once, agrees with",
        "the number it was supposed to improve on.",
        "",
        "That agreement is worth exactly as much as the assumption underneath it, so the honest",
        "output is not a contribution figure — it is the value of the assumption at which the",
        "conclusion changes:",
        "",
        "| Marginal cost per 1k of balance | Mean contribution | Customers below zero | Most profitable product | Agreement with the revenue ranking |",
        "|---:|---:|---:|---|---:|",
    ]
    for point in sensitivity.points:
        if round(point.per_balance * 100) % 6:
            continue
        lines.append(
            f"| {_money(point.per_balance)} | {_money(point.mean_contribution)} | "
            f"{point.negative_customers:,} | {point.best_plan} | {_pct(point.top_third_overlap, 0)} |"
        )

    lines += [
        "",
        "Three thresholds, all inside the range a real operator would argue about, and all solved",
        "rather than read off the sweep — contribution is linear in the assumption, so where two",
        "tariffs cross has an exact answer:",
        "",
    ]
    if sensitivity.overtaken_per_gb is not None:
        lines.append(
            f"- at **{_money(sensitivity.overtaken_per_gb)}/1k**, {sensitivity.top_product} stops being "
            f"the most profitable tariff and {sensitivity.overtaken_by} takes over;"
        )
    if inversion is not None:
        lines.append(
            f"- at **{_money(inversion)}/1k**, {sensitivity.top_product} — the most expensive product on the "
            f"price list — falls below {sensitivity.cheapest_plan}, the cheapest;"
        )
    if ruin is not None:
        lines.append(
            f"- at **{_money(ruin)}/1k**, the average {sensitivity.top_product} customer stops covering "
            f"their own cost."
        )
    lines += [
        "",
        "Nobody in the analytics chain owns that number. It comes from treasury or from",
        "finance, it is rarely written down anywhere the customer-value model can see it, and the",
        "value model is a function of it. Publishing a contribution ranking without publishing the",
        "cost it assumes is publishing somebody else's opinion as a result.",
        "",
    ]
    return lines


def _horizon(result: CaseResult) -> list[str]:
    comparison, cancellation = result.horizons, result.cancellation
    assert comparison is not None and cancellation is not None
    hazard = comparison.hazard

    lines = [
        "## Contribution to value: the horizon, which is the whole answer",
        "",
        f"Case 02 credited a saved customer with **{comparison.flat_months:.0f} months** of margin.",
        "Every customer, whatever their risk.",
        "",
        "**The number barely mattered. Its flatness did.** Swapping twelve months for any other",
        "constant leaves case 02's list almost exactly where it was — the horizon enters its ranking",
        "only through the offer cost, which is small beside the value at risk:",
        "",
        "| Instead of twelve months, flat | Names kept from case 02's list |",
        "|---|---:|",
    ]
    for point in sorted(result.flat_sweep, key=lambda p: p.months):
        label = "no horizon at all" if point.months > 1000 else f"{point.months:.0f} months"
        lines.append(f"| {label} | {_pct(point.overlap_with_flat)} |")

    lines += [
        "",
        "So the choice of twelve was defensible where it was made, and it is not what this section",
        "is about. What was never argued for is that every customer gets the *same* number — and a",
        "90-day churn probability already implies a different one for each. Read as a constant",
        "monthly hazard, `(1 − h)³ = 1 − p`, the expected remaining life of a memoryless customer is",
        "`1/h`:",
        "",
    ]
    return lines + [
        "| | |",
        "|---|---:|",
        f"| Shortest implied life in the base | {hazard.spread[0]:.1f} months |",
        f"| 10th percentile | {hazard.quantile(0.1):.1f} months |",
        f"| Median | {hazard.quantile(0.5):.1f} months |",
        f"| Ceiling applied | {result.cap_months:.0f} months |",
        f"| Customers with less life than case 02 credits them | "
        f"{comparison.below_flat:,} ({_pct(comparison.below_flat_share)}) |",
        "",
        "The ceiling is a policy, not an estimate. Without one the lowest-risk customers are credited",
        "with thirty years of margin, and a lifetime value model comes to be dominated by its least",
        "certain tail.",
        "",
        "### And then the risk cancels",
        "",
        "A save is worth the life it preserves. The higher the hazard, the less life there is to",
        "preserve — so the `p` in the numerator of an expected value and the `1/h` in its value term",
        "very nearly cancel. Measured across this base:",
        "",
        "| | |",
        "|---|---:|",
        f"| Mean of `p / h` | **{cancellation.mean_ratio:.4f}** |",
        f"| Range | {cancellation.spread[0]:.2f} to {cancellation.spread[1]:.2f} |",
        f"| The label window, in months | {cancellation.window:.0f} |",
        "",
        "`p / h` is the label window, to within a few percent, for every customer in the base. Under a",
        "hazard-consistent horizon the expected value of a retention contact is approximately",
        "`3 × save rate × margin × revenue` — **and churn risk has dropped out of it**, except through",
        "the offer cost, which a riskier customer incurs more often and which therefore makes them",
        "slightly *less* attractive. The same offer cost that made the flat horizon nearly inert is",
        "the only thing left carrying risk once the horizon varies.",
        "",
        "That is not an argument against retention targeting. It is the price of one unstated",
        "assumption: whether a save **changes** a customer's hazard or merely **postpones one draw**",
        "of it. Case 02's flat horizon silently assumes the first. Nothing in this data model records",
        "which is true, and — unusually for this track — the answer key cannot help. It records what a",
        "customer would have done without the campaign inside the same 90 days; what a saved customer",
        "does in the years afterwards is not unobserved here, it does not exist. The world ends at the",
        "cutoff.",
        "",
    ]


def _bakeoff(result: CaseResult) -> list[str]:
    bakeoff = result.bakeoff
    full = result.full_model
    assert bakeoff is not None and full is not None

    lines = [
        "## Four lists from one set of scores",
        "",
        "Same customers, same probabilities, same revenue figure, same commercial constants, same",
        f"capacity of **{bakeoff.capacity:,} contacts**. The only thing that varies is how many months",
        "a save is credited with.",
        "",
        "| List | Churners caught | Mean revenue | Mean predicted risk |",
        "|---|---:|---:|---:|",
    ]
    for target in bakeoff.lists:
        profile = bakeoff.profile(target.name)
        lines.append(
            f"| {target.name} | {profile.churners_caught:,} | {_money(profile.mean_revenue)} | "
            f"{_pct(profile.mean_probability)} |"
        )

    lines += ["", "How much they share:", "", "| | |", "|---|---:|"]
    for i, left in enumerate(bakeoff.lists):
        for right in bakeoff.lists[i + 1:]:
            lines.append(f"| {left.name} vs {right.name} | {_pct(left.overlap(right), 1)} |")

    hazard_list = next(t for t in bakeoff.lists if "hazard" in t.name)
    revenue_list = next(t for t in bakeoff.lists if t.name == "by revenue alone")
    flat_list = next(t for t in bakeoff.lists if "flat" in t.name)

    unbounded = max(result.flat_sweep, key=lambda p: p.months) if result.flat_sweep else None
    lines += [
        "",
        f"Letting the horizon vary per customer moves **{_pct(1 - flat_list.overlap(hazard_list))}** of",
        "the names on case 02's list"
        + (f", against {_pct(1 - unbounded.overlap_with_flat)} for dropping the horizon entirely and "
           f"keeping it flat." if unbounded else "."),
        f"And the hazard-consistent list is {_pct(hazard_list.overlap(revenue_list))} the same as ranking",
        "by revenue and not running a churn model at all — which is the cancellation above, in the",
        "form a campaign manager would meet it.",
        "",
        "### The table that cannot settle it",
        "",
        "Scoring each list under each accounting produces this:",
        "",
        "| List | " + " | ".join(a.name for a in bakeoff.accountings) + " |",
        "|---|" + "---:|" * len(bakeoff.accountings),
    ]
    for target in bakeoff.lists:
        cells = " | ".join(
            _money(bakeoff.profit[(target.name, a.name)], 0) for a in bakeoff.accountings
        )
        lines.append(f"| {target.name} | {cells} |")

    lines += [
        "",
        "**Every list wins under its own accounting, and that is arithmetic rather than evidence.**",
        "Expected realised profit from contacting a customer *is* the expected value the list was",
        "sorted by, so sorting by it maximises the total at any capacity, by construction. The table",
        "cannot be read as a bake-off. It restates the assumption as a number.",
        "",
        "Two things can overturn it, and neither is about the horizon: sampling noise in who actually",
        "churned, and miscalibration. Case 02 measured the second — a calibration slope of 0.77 out of",
        "time — and reported it as a modelling nuance, because for a *ranking* it is one. The moment",
        "the same score is turned into money, calibration is not a nuance; it is the entire",
        "conversion factor.",
        "",
        "### Both changes at once",
        "",
        "For completeness, and labelled as what it is: replacing case 02's value figure **and** its",
        "horizon — contribution instead of billed revenue, implied life instead of twelve months —",
        f"leaves **{_pct(full.overlap)}** of its list standing. The customers it swaps in are worth",
        f"{_money(full.case04_mean_contribution)} a month in contribution against",
        f"{_money(full.case02_mean_contribution)} for the ones it drops. That number attributes",
        "nothing; it is here so the two changes are not quietly summed elsewhere.",
        "",
    ]
    return lines


def _axis(result: CaseResult) -> list[str]:
    axis = result.axis
    assert axis is not None
    still = axis.still_plans
    worst = axis.worst_plan

    lines = [
        "## What this does to case 01's value axis",
        "",
        "Case 01 measured how much of the base changes segment in six months and found the movement",
        "is almost entirely on the risk axis — 41.3% against 6.0% for value — and concluded that",
        f"value is the slow axis. Measured here with the same rule: **{_pct(axis.share_moved)}** of the",
        f"{axis.n:,} customers present at both cutoffs change value band. The aggregate reproduces.",
        "",
        "Where it comes from does not:",
        "",
        "| Product | Fee | Customers | Changed band | Distance from the nearest cut |",
        "|---|---:|---:|---:|---:|",
    ]
    for product in axis.by_product:
        distance = "—" if product.distance_to_cut_in_sd == float("inf") else f"{product.distance_to_cut_in_sd:.1f} sd"
        lines.append(
            f"| {product.product_id} | {_money(product.monthly_fee, 0)} | {product.customers:,} | "
            f"{product.moved:,} ({_pct(product.share_moved)}) | {distance} |"
        )

    lines += [
        "",
        f"{_plural(len(still), 'tariff')} of {len(axis.by_product)} contributed **not one customer**. "
        f"{worst.product_id} contributed {_pct(worst.share_moved)} of its own book, and "
        f"{_pct(axis.concentration)} of every mover in the base.",
        "",
        "The mechanism is the estimator noise from two sections ago. A customer's measured ARPU is",
        f"their tariff plus about {_pct(result.estimator.mean_relative_sd if result.estimator else 0.0)}",
        "of noise; the axis is then cut into three bands. A tariff whose fee sits far from every cut",
        "has a band that is a constant. A tariff sitting on one has a band decided by three months of",
        "billing noise, re-drawn every time the analysis runs.",
        "",
        "An aggregate of *constant* and *coin flip* reads as *fairly stable*. It is neither, and the",
        "difference matters because case 01 hands each cell a different play: those customers get a",
        "different action every quarter for no commercial reason whatsoever.",
        "",
        "One detail worth keeping, because it is the kind of thing a rule of thumb gets wrong: a",
        "tariff can sit barely one standard deviation from a threshold and still never cross it.",
        "Measured ARPU is the fee *plus a non-negative* term, so its distribution has a hard floor at",
        "the fee — and a cut landing exactly there is a wall, not a boundary. Which tariffs move is",
        "counted from the data, not inferred from the distance.",
        "",
    ]
    return lines


def _not_sold(result: CaseResult) -> list[str]:
    collection = result.collection
    bridge = result.bridge
    sensitivity = result.sensitivity
    assert collection is not None and bridge is not None and sensitivity is not None

    return [
        "## What this case does not sell",
        "",
        "**That the collection shortfall concentrates in the customers about to leave.** It was the",
        "premise the section was written on and the mechanism is in the data model. Measured, the",
        f"correlation is {collection.risk_correlation:+.4f} against a standard error of "
        f"{collection.risk_correlation_se:.4f}, and it is not stable enough to have a sign: five folds",
        f"of this same base span {collection.fold_range[0]:+.4f} to {collection.fold_range[1]:+.4f}. The",
        "claim was dropped, not the measurement — and the flag that would report it is still computed",
        "from the data, so a world where it is true would say so.",
        "",
        "**That the ARPU bridge found anything.** It reconciles exactly and reports movements inside",
        "their own error bars, because this world has no tariff migration and nobody ever stops being",
        "invoiced. That is a limitation of the data model, stated as one. The section is kept because",
        "an interval that says *nothing moved* is a different artefact from an unrun analysis — but it",
        "is not a finding about telcos.",
        "",
        "**That contribution beats revenue as a value measure.** At the declared marginal data cost",
        f"the two rank the base {_pct(sensitivity.at(result.cost_model.per_balance).top_third_overlap)} the",
        "same. The decomposition earns its place by producing the *break-even* — the cost at which the",
        "answer flips — not by producing a better ranking, which at this assumption it does not.",
        "",
        "**That the hazard-consistent horizon is the right one.** It is the one that is internally",
        "consistent with the churn model already in production, which is a real argument and not a",
        "proof. Whether a save changes a customer's hazard or postpones one draw of it is a question",
        "about the world, and this dataset — answer key included — does not contain the answer. The",
        "deliverable is that the choice is load-bearing and undeclared, not that it has been made.",
        "",
    ]


def _reuse(result: CaseResult) -> list[str]:
    return [
        "## Reuse, so the cases do not drift",
        "",
        "The churn model, feature builder, scoreable population and commercial constants are case",
        "02's, imported and refitted rather than quoted. The save rate is the "
        f"**{_pct(result.save_rate)}** case 05 measured against its control, not the 25% case 02 had",
        "to assume. The band machinery in the value-axis section is case 01's own `quantile_cuts` and",
        "`band_of`, so the claim about its axis is made with its own instrument.",
        "",
        "The answer key is never opened. Not as discipline — it has nothing to say about a horizon",
        "that extends past the end of the world it describes. Cases 05, 03 and 01 all consult",
        "`churn_potential_outcomes`, each through case 05's quarantined module; this one has no",
        "question it could answer, and a test asserts it stays that way.",
        "",
        "## Reproducing",
        "",
        "```bash",
        "uv run run.py                       # defaults: 5,000 customers, seed 42",
        "uv run run.py --seed 7              # a different world; the robustness numbers above",
        "uv run run.py --per-balance 0.32         # re-price at the inversion point",
        "uv run run.py --cap-months 12       # case 02's ceiling, applied as a ceiling on life",
        "```",
        "",
        "Two consecutive runs are byte-for-byte identical. Every table above is generated from the",
        "run that wrote this file.",
        "",
    ]


def render(result: CaseResult) -> str:
    sections = [
        _header(result),
        _base(result),
        _level(result),
        _movement(result),
        _collection(result),
        _contribution(result),
        _horizon(result),
        _bakeoff(result),
        _axis(result),
        _not_sold(result),
        _reuse(result),
    ]
    return "\n".join(line for section in sections for line in section).rstrip() + "\n"
